// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://gbbqaggxbzonbaiwxpjc.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImdiYnFhZ2d4YnpvbmJhaXd4cGpjIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTE4ODIyMTAsImV4cCI6MjA2NzQ1ODIxMH0.uj83q4HDJAeLVycMerxkd29sIJtkK89quZAxN0_LbUM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});